"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertCircle, ArrowLeft, ArrowRight, Bot, Check, ChevronRight, Layers, Sparkles, Target } from "lucide-react";
import LandingNavbar from "@/components/LandingNavbar";
import Footer from "@/components/Footer";
import automatedResources from "@/data/automation-resources.json";

const gtmCases = [
  { tag: "Insurance", title: "A new insurance brand, built from zero to a 4,000+ audience.", challenge: "A newly launched insurance brand needed credibility and a LinkedIn audience from scratch in a crowded, trust-sensitive market.", strategy: ["Content-led LinkedIn growth", "Educational, data-led posts", "Consistent thought leadership and engagement"], results: [["0 → 4,000+", "Followers in 2 months"], ["Niche", "Highly engaged audience"], ["Organic", "Growth engine established"]] },
  { tag: "Transportation & Manufacturing • AI", title: "Doubling connection acceptance for a deep-tech AI company.", challenge: "An AI solutions company was stuck at a 15–20% connection-acceptance rate and weak overall outreach.", strategy: ["Refined ICP targeting", "Personalised connection requests", "Improved messaging and follow-up"], results: [["30%", "Acceptance, up from 15–20%"], ["15%", "Response rate"], ["5–10%", "Call-booking rate"]] },
  { tag: "Martech & AEO", title: "A predictable pipeline for a martech founder across two regions.", challenge: "A martech startup founder needed predictable pipeline among MSME founders in the US and Middle East.", strategy: ["Targeted LinkedIn outreach", "Sharp-ICP personalisation", "Structured multi-step follow-ups"], results: [["40%", "Connection acceptance"], ["20%", "Response rate"], ["15–20", "Qualified calls per month"]] },
  { tag: "Enterprise • AI Voice", title: "Opening enterprise doors for an AI voice-agent platform.", challenge: "An AI voice-agent startup needed access to senior enterprise decision-makers who are hard to reach cold.", strategy: ["Named enterprise accounts", "Senior stakeholder outreach", "Personalised account sequences"], results: [["10–15", "Enterprise opportunities in 2 months"], ["Senior", "Decision-makers reached"], ["2–3%", "Conversion rate"]] },
  { tag: "Financial Advisory • AI", title: "Winning trust first for an AI-powered financial platform.", challenge: "Prospects were reluctant to share financial information early, stalling qualification.", strategy: ["Trust-first outreach", "AI conversational workflows", "Chatbot-assisted qualification"], results: [["20–25%", "Connection acceptance"], ["Higher", "Trust during qualification"], ["Better", "Qualified-lead quality"]] },
];

const workflows = [
  { tag: "Lead Qualification", title: "AI lead qualification, from inbound form to scored prospect.", context: "High volumes of website enquiries made manual qualification slow, inconsistent, and resource-heavy.", steps: ["Capture every website form", "Research the lead and company", "Score company size, industry, role, and relevance", "Categorise and store qualified prospects"], impacts: ["Manual qualification eliminated", "Faster sales response", "Structured prospect database"] },
  { tag: "Social Engagement", title: "Instagram DM automation that captures every warm commenter.", context: "An automated engagement workflow built with ManyChat and n8n for viral-content conversations.", steps: ["Monitor posts and Reels", "Detect defined keyword comments", "Trigger a personalised Instagram DM", "Store lead details centrally for CRM"], impacts: ["Instant engagement", "Automated capture", "More conversion opportunities"] },
  { tag: "Marketing Integrity", title: "Inventory validation that stops misleading promotions.", context: "Every product offer is verified before publishing, and revalidated when stock or discounts change.", steps: ["Verify product and inventory", "Validate discounts and expiry dates", "Check product URLs", "Block offers when any check fails"], impacts: ["Misleading promotions prevented", "Fewer advertising errors", "Customer trust protected"] },
  { tag: "Decision Support", title: "A business decision engine that recommends, but never acts alone.", context: "Data-driven recommendations keep every business decision under human control.", steps: ["Collect data across ads, web, social, and product", "Identify high-performing and weak initiatives", "Recommend scale, pause, fix, or investigate", "Route every action to human approval"], impacts: ["Faster decisions", "Better operational visibility", "Human oversight maintained"] },
  { tag: "Ad Compliance", title: "Compliance validation that protects the ad account.", context: "Campaigns are checked against Meta and Google Ads policy before launch and after every change.", steps: ["Review creatives, copy, landing pages, and targeting", "Flag policy violations", "Recommend corrections", "Require approval and revalidate changes"], impacts: ["Lower ad-rejection rates", "Accounts protected", "Ongoing compliance"] },
];

export default function CaseStudiesPage() {
  const [activeTab, setActiveTab] = useState<"all" | "gtm" | "automation">("all");
  const showGtm = activeTab === "all" || activeTab === "gtm";
  const showAutomation = activeTab === "all" || activeTab === "automation";

  const caseStudyResources = automatedResources.filter(
    (resource) => resource.type?.trim().toLowerCase() === "case-study"
  );

  const latestAutomatedCaseStudy = [...caseStudyResources].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  )[0];

  return <div className="case-studies-light min-h-screen bg-white text-slate-950 selection:bg-blue-200 selection:text-blue-950"><LandingNavbar /><main className="pt-14">

    <Link
      href="/resources/automation?type=case-study"
      className="mx-auto block max-w-7xl border-b border-indigo-500/20 bg-indigo-500/10 px-4 py-5 hover:bg-indigo-500/15 sm:px-6 lg:px-8"
    >
      <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-400">
        <Sparkles className="h-4 w-4" />
        Automation Daily Updated Case Study Resources
      </div>
      <h2 className="mt-2 text-xl font-extrabold text-white">
        {latestAutomatedCaseStudy?.title || "Latest Automated Case Study"}
      </h2>
      <p className="mt-1 text-sm text-slate-400">
        {latestAutomatedCaseStudy?.description ||
          "New case studies are automatically added and updated here."}
      </p>
    </Link>

    <div className="sticky top-14 z-40 border-b border-slate-800/80 bg-[#0B1120]/90 px-4 py-3.5 backdrop-blur-md sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="group inline-flex items-center gap-2 text-xs font-bold text-slate-400 hover:text-blue-400"><ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" /> Back to home</Link><span className="hidden items-center gap-2 text-xs font-semibold text-slate-400 sm:flex">Leadnius <ChevronRight className="h-3.5 w-3.5 text-slate-600" /><span className="text-blue-400">Verified case studies & automations</span></span><a href="https://calendar.app.google/UWRRkZgCUAzc2i9i8" target="_blank" rel="noreferrer" className="hidden rounded-full border border-blue-500/30 bg-blue-600/20 px-3.5 py-1.5 text-xs font-bold text-blue-300 hover:bg-blue-600/30 sm:inline-flex">Book strategy call <ArrowRight className="ml-1 h-3.5 w-3.5" /></a></div></div>

    <section className="relative overflow-hidden border-b border-slate-800/60 py-16 sm:py-20"><div className="pointer-events-none absolute left-1/2 top-0 h-[500px] w-[800px] -translate-x-1/2 rounded-full bg-gradient-to-tr from-blue-600/15 via-indigo-600/15 to-purple-600/15 blur-[140px]" /><div className="relative mx-auto grid max-w-7xl grid-cols-1 items-center gap-12 px-4 sm:px-6 lg:grid-cols-12 lg:px-8"><div className="space-y-6 lg:col-span-7"><span className="inline-flex items-center gap-2 rounded-full border border-blue-500/30 bg-blue-500/10 px-3.5 py-1.5 text-xs font-bold uppercase tracking-wider text-blue-400"><Sparkles className="h-3.5 w-3.5" /> Verified client outcomes & engineering</span><h1 className="text-4xl font-extrabold leading-none tracking-tight text-white sm:text-6xl">Proof, not <span className="bg-gradient-to-r from-blue-400 via-indigo-300 to-purple-400 bg-clip-text text-transparent">promises.</span></h1><p className="max-w-2xl text-base leading-relaxed text-slate-300 sm:text-lg">Two sides of the same engine, both measured. GTM systems turn cold networks into booked pipeline; AI automation workflows remove the manual work behind them. Every result below is real and every client is anonymous.</p><div className="flex flex-wrap gap-4"><a href="#gtm-section" onClick={() => setActiveTab("gtm")} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-xs font-bold text-white shadow-lg shadow-blue-600/30 transition-all hover:scale-105 hover:bg-blue-500">See the growth results <ArrowRight className="h-4 w-4" /></a><a href="#automation-section" onClick={() => setActiveTab("automation")} className="rounded-xl border border-slate-700 bg-slate-800/80 px-6 py-3.5 text-xs font-bold text-slate-200 transition-colors hover:bg-slate-800 hover:text-white">See the automations</a></div></div><SnapshotPanel /></div></section>

    <section className="border-b border-slate-800/60 bg-slate-950/50 py-12"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-5 px-4 sm:grid-cols-4 sm:px-6 lg:px-8"><Stat value="4,000+" label="LinkedIn followers built from zero in two months" /><Stat value="40%" label="Peak cold-outreach acceptance rate" /><Stat value="15–20" label="Qualified sales calls booked each month" /><Stat value="10–15" label="Enterprise opportunities in two months" /></div></section>

    <section className="border-b border-slate-800/60 py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto mb-12 max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-wider text-blue-400">How to read this page</p><h2 className="mt-2 text-3xl font-extrabold text-white sm:text-4xl">Two tracks. One system underneath.</h2><p className="mt-4 text-sm leading-relaxed text-slate-400 sm:text-base">Growth work books the meetings; automation work makes the motion run without manual effort. Most engagements use both.</p><div className="mt-8 inline-flex max-w-full flex-wrap justify-center gap-1 rounded-2xl border border-slate-800 bg-slate-900 p-1.5">{(["all", "gtm", "automation"] as const).map((tab) => <button type="button" key={tab} onClick={() => setActiveTab(tab)} className={`rounded-xl px-4 py-2 text-xs font-bold transition-all ${activeTab === tab ? "bg-blue-600 text-white shadow-md" : "text-slate-400 hover:text-white"}`}>{tab === "all" ? "All case studies" : tab === "gtm" ? "Track A: GTM growth" : "Track B: AI workflows"}</button>)}</div></div><div className="grid gap-8 md:grid-cols-2"><TrackCard title="Outreach that books real calls" label="Track A • GTM & LinkedIn growth" desc="Targeted, personalised campaigns tuned to a sharp ICP — measured in acceptance, replies, and booked meetings." action={() => setActiveTab("gtm")} /><TrackCard title="Systems that remove the busywork" label="Track B • AI automation workflows" desc="Lead qualification, engagement, validation, and decision workflows built to run automatically while humans retain control." action={() => setActiveTab("automation")} indigo /></div></div></section>

    {showGtm && <section id="gtm-section" className="scroll-mt-28 border-b border-slate-800/60 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionLead label="Track A • GTM & LinkedIn growth" title="From cold network to booked pipeline." desc="Five outreach engagements across insurance, deep-tech, martech, and financial services. Different markets, the same playbook: sharpen the ICP, personalise, and follow up with structure." /> <div className="space-y-8">{gtmCases.map((study, index) => <article key={study.title} className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 transition-colors hover:border-blue-500/40 sm:p-10"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><span className="rounded-full border border-blue-500/30 bg-blue-500/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-blue-400">{study.tag}</span><span className="font-mono text-xs font-bold text-slate-500">Case {String(index + 1).padStart(2, "0")}</span></div><h3 className="mb-6 text-2xl font-extrabold leading-snug text-white sm:text-3xl">{study.title}</h3><div className="mb-8 grid gap-6 md:grid-cols-2"><InfoBlock icon={AlertCircle} title="Challenge" text={study.challenge} /><div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-5"><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><Target className="h-4 w-4 text-blue-400" /> Strategy</p><ul className="space-y-2 text-sm text-slate-300">{study.strategy.map((item) => <li key={item} className="flex gap-2"><span className="text-blue-400">›</span>{item}</li>)}</ul></div></div><div className="border-t border-slate-800 pt-6"><p className="mb-4 text-xs font-bold uppercase tracking-wider text-slate-400">Quantified results</p><div className="grid gap-4 sm:grid-cols-3">{study.results.map(([metric, label]) => <Metric key={label} value={metric} label={label} />)}</div></div></article>)}</div></div></section>}

    {showAutomation && <section id="automation-section" className="scroll-mt-28 border-b border-slate-800/60 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionLead label="Track B • AI automation workflows" title="The busywork, engineered away." desc="Five production workflows that research, qualify, validate, and recommend automatically. Each keeps a human in control exactly where judgment matters." indigo /> <div className="space-y-8">{workflows.map((workflow, index) => <article key={workflow.title} className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6 transition-colors hover:border-indigo-500/40 sm:p-10"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><span className="rounded-full border border-indigo-500/30 bg-indigo-500/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-indigo-400">{workflow.tag}</span><span className="font-mono text-xs font-bold text-slate-500">Workflow {String(index + 1).padStart(2, "0")}</span></div><h3 className="mb-6 text-2xl font-extrabold leading-snug text-white sm:text-3xl">{workflow.title}</h3><div className="mb-8 grid gap-6 lg:grid-cols-12"><InfoBlock icon={Layers} title="Purpose" text={workflow.context} className="lg:col-span-5" /><div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-6 lg:col-span-7"><p className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><Bot className="h-4 w-4 text-blue-400" /> How it runs</p><ol className="space-y-3">{workflow.steps.map((step, stepIndex) => <li key={step} className="flex items-start gap-3 text-sm text-slate-300"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded border border-blue-500/40 bg-blue-500/20 font-mono text-[11px] font-bold text-blue-400">{stepIndex + 1}</span>{step}</li>)}</ol></div></div><div className="border-t border-slate-800 pt-6"><p className="mb-4 text-xs font-bold uppercase tracking-wider text-slate-400">Business impact delivered</p><div className="flex flex-wrap gap-2.5">{workflow.impacts.map((impact) => <span key={impact} className="inline-flex items-center gap-1.5 rounded-xl border border-emerald-500/30 bg-emerald-950/50 px-3.5 py-1.5 text-xs font-semibold text-emerald-300"><Check className="h-3.5 w-3.5" /> {impact}</span>)}</div></div></article>)}</div></div></section>}

    <section className="border-b border-slate-800/60 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto mb-12 max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-wider text-blue-400">The through-line</p><h2 className="mt-2 text-3xl font-extrabold text-white sm:text-5xl">What every result above has in common.</h2></div><div className="grid gap-8 md:grid-cols-3">{[["A sharp ICP", "Every growth number started by narrowing the target until the message could be personal, not generic."], ["Structured follow-up", "Booked calls came from sequences, not single touches — persistence engineered into the system."], ["Human in the loop", "Automation removed busywork, while people kept control of every decision that carried real risk."]].map(([title, desc], index) => <article key={title} className="rounded-3xl border border-slate-800 bg-slate-900/80 p-8"><span className="font-mono text-sm font-bold text-blue-400">0{index + 1}</span><h3 className="mb-2 mt-3 text-xl font-extrabold text-white">{title}</h3><p className="text-sm leading-relaxed text-slate-400">{desc}</p></article>)}</div></div></section>

    <section className="relative overflow-hidden py-24"><div className="relative mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><div className="relative overflow-hidden rounded-3xl border border-blue-500/40 bg-gradient-to-br from-blue-950/60 via-slate-900 to-indigo-950/60 p-10 text-center shadow-2xl sm:p-16"><div className="pointer-events-none absolute right-0 top-0 h-96 w-96 rounded-full bg-blue-500/10 blur-3xl" /><div className="relative"><h2 className="mb-6 text-3xl font-extrabold text-white sm:text-5xl">Want results like these for your pipeline?</h2><p className="mx-auto mb-10 max-w-2xl text-base leading-relaxed text-slate-300 sm:text-lg">Tell us your market and stage. We will show you which play fits and what an engineered version would look like for you.</p><div className="flex flex-col justify-center gap-4 sm:flex-row"/><Link href="/login" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-8 py-4 text-sm font-bold text-white shadow-xl shadow-blue-600/30 transition-all hover:scale-105 hover:bg-blue-500">Book a strategy call <ArrowRight className="h-4 w-4" /></Link><Link href="/#services" className="rounded-xl border border-slate-700 bg-slate-800/80 px-8 py-4 text-sm font-bold text-slate-300 hover:bg-slate-800 hover:text-white">See all services</Link></div></div></div></section>
  </main>
  <Footer />
</div>;
}

function SnapshotPanel() { return <div className="lg:col-span-5"><div className="rounded-3xl border border-blue-500/30 bg-slate-900/90 p-6 shadow-2xl sm:p-8"><div className="mb-4 flex items-center justify-between border-b border-slate-800 pb-4 font-mono text-xs"><span className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-blue-400"><span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse" /> Results • snapshot</span><span className="text-slate-500">Anonymised</span></div><div className="space-y-3.5">{[["LinkedIn network growth", "0 → 4,000+ (2 mos)"], ["Connection acceptance rate", "Up to 40%"], ["Qualified calls booked", "15–20 / mo"], ["Enterprise pipeline opps", "10–15 opps"], ["Manual lead qualification", "100% automated"]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800/80 bg-slate-950/60 p-3 text-xs"><span className="text-slate-300">{label}</span><span className="shrink-0 rounded-full border border-blue-500/20 bg-blue-500/10 px-2.5 py-1 font-mono font-bold text-blue-300">{value}</span></div>)}</div></div></div>; }
function Stat({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5 text-center"><p className="text-2xl font-extrabold text-blue-400 sm:text-4xl">{value}</p><p className="mt-1 text-xs leading-snug text-slate-400">{label}</p></div>; }
function TrackCard({ label, title, desc, action, indigo = false }: { label: string; title: string; desc: string; action: () => void; indigo?: boolean }) { return <article className={`flex flex-col justify-between rounded-3xl border bg-slate-900/90 p-8 ${indigo ? "border-indigo-500/30" : "border-blue-500/30"}`}><div><p className={`text-xs font-bold uppercase tracking-wider ${indigo ? "text-indigo-400" : "text-blue-400"}`}>{label}</p><h3 className="mb-3 mt-2 text-2xl font-extrabold text-white">{title}</h3><p className="mb-6 text-sm leading-relaxed text-slate-300">{desc}</p></div><button type="button" onClick={action} className={`w-fit text-xs font-bold ${indigo ? "text-indigo-400" : "text-blue-400"}`}>Inspect case studies →</button></article>; }
function SectionLead({ label, title, desc, indigo = false }: { label: string; title: string; desc: string; indigo?: boolean }) { return <div className="mb-12 max-w-3xl"><span className={`inline-flex rounded-full border px-3.5 py-1.5 text-xs font-bold uppercase tracking-wider ${indigo ? "border-indigo-500/20 bg-indigo-500/10 text-indigo-400" : "border-blue-500/20 bg-blue-500/10 text-blue-400"}`}>{label}</span><h2 className="mb-3 mt-4 text-3xl font-extrabold tracking-tight text-white sm:text-5xl">{title}</h2><p className="text-sm leading-relaxed text-slate-400 sm:text-base">{desc}</p></div>; }
function InfoBlock({ icon: Icon, title, text, className = "" }: { icon: typeof AlertCircle; title: string; text: string; className?: string }) { return <div className={`rounded-2xl border border-slate-800 bg-slate-950/60 p-5 ${className}`}><p className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><Icon className="h-4 w-4 text-blue-400" /> {title}</p><p className="text-sm leading-relaxed text-slate-300">{text}</p></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl border border-slate-800 bg-slate-950/90 p-4"><p className="text-2xl font-extrabold text-blue-400">{value}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>; }