import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Bot,
  Building2,
  Cpu,
  Database,
  FileText,
  Filter,
  Globe,
  Layers,
  Mail,
  PhoneCall,
  Radio,
  RefreshCw,
  Search,
  Send,
  Share2,
  Target,
  TrendingUp,
  Video,
  Workflow,
  Zap,
} from "lucide-react";
import type { ServiceId } from "@/lib/services";

type FlowStep = { num: string; title: string; desc: string; icon?: LucideIcon };
type Card = { eyebrow: string; title: string; desc: string; bullets: string[]; icon?: LucideIcon };
type Metric = { label: string; value: string; desc: string };

export type ServicePageContent = {
  id: Exclude<ServiceId, "product-marketing">;
  title: string;
  icon: LucideIcon;
  heroLead: string;
  heroHighlight: string;
  intro: string;
  primaryCta: string;
  secondaryCta: string;
  highlights: [string, string];
  panel: { title: string; badge: string; rows: { label: string; value: string }[] };
  stats: { value: string; label: string }[];
  challenge: { eyebrow: string; title: string; desc: string; oldLabel: string; oldBullets: string[]; newLabel: string; newBullets: string[] };
  flow: { eyebrow: string; title: string; desc: string; steps: FlowStep[] };
  cards: { eyebrow: string; title: string; desc: string; items: Card[] };
  focus: { eyebrow: string; title: string; desc: string; items: Card[] };
  metrics: Metric[];
  faqs: { q: string; a: string }[];
  final: { title: string; desc: string; cta: string };
  calculator?: true;
};

export const servicePageContent: Record<Exclude<ServiceId, "product-marketing">, ServicePageContent> = {
  "gtm-engineering": {
    id: "gtm-engineering", title: "AI GTM Engineering", icon: Cpu,
    heroLead: "Pipeline you can", heroHighlight: "trace back to a signal.",
    intro: "Outbound isn't broken. Yours is just unengineered. Buying committees have never been noisier, and volume no longer wins. We build the system that reaches the right account the moment it's in-market, with a message assembled from its own signals — and syncs every touch back to your CRM so nothing leaks.",
    primaryCta: "Build your GTM system", secondaryCta: "See how it works", highlights: ["Signal-based architecture", "100% CRM hygiene sync"],
    panel: { title: "GTM command center · live", badge: "this week", rows: [{ label: "New in-market signals", value: "+24 today" }, { label: "Accounts enriched", value: "waterfall" }, { label: "Meetings booked", value: "this wk" }, { label: "Reply rate vs cold", value: "3–5× cold" }, { label: "Pipeline → CRM", value: "synced" }] },
    stats: [{ value: "2 weeks", label: "to a live signal motion" }, { value: "2–3×", label: "single-source data coverage" }, { value: "Live", label: "CRM hygiene & reporting" }, { value: "Yours", label: "the engine at the end" }],
    challenge: { eyebrow: "The shift", title: "Winning outbound stopped being about volume.", desc: "The old motion was a numbers game: scrape more, send more, hope. The new motion is an engineering problem: detect intent, enrich deeply, score for fit, and route effort only to accounts that are actually in the market.", oldLabel: "Spray & pray motion", oldBullets: ["Scraped lists that never sync back to the CRM", "The same generic pitch to every persona", "No signals, no timing, no idea who is in-market", "SDRs drowning in manual research and copy-paste", "Reporting that arrives too late to act on"], newLabel: "Engineered by Leadnius", newBullets: ["Deep waterfall enrichment that fills gaps other tools miss", "Messaging per persona built from real buyer language", "Fit + intent scoring that routes effort to the right accounts", "Enrichment and orchestration that run without babysitting", "Live dashboards your Monday review reads in ten minutes"] },
    flow: { eyebrow: "Always-on machine", title: "The system behind a signal-based GTM motion.", desc: "Signals become deeply enriched, prioritised accounts, then become coordinated outreach and clean CRM intelligence.", steps: [{ num: "01", title: "Signal", desc: "Funding, hiring, tech-stack changes, site visits, and product triggers tracked live.", icon: Radio }, { num: "02", title: "Enrich", desc: "Waterfall data per account — the next provider fires when the last one comes up empty.", icon: Database }, { num: "03", title: "Score", desc: "Fit + intent combined so the best accounts surface first, not the loudest.", icon: Filter }, { num: "04", title: "Sequence", desc: "Email and LinkedIn in sync, personalised from the account's own signals.", icon: Send }, { num: "05", title: "Route", desc: "Ranked queues and clean handoffs so reps work the right account next.", icon: Workflow }, { num: "06", title: "Sync", desc: "Every touch written back to the CRM, stages updated, reporting live.", icon: RefreshCw }] },
    cards: { eyebrow: "Two engines", title: "Outbound precision, then account-level depth.", desc: "We engineer the operating layer and the account-based motion together.", items: [{ eyebrow: "Engine 01 · Revenue ops", title: "GTM Systems Engineering", desc: "The operating system behind high-conversion outbound and a CRM your team can trust.", bullets: ["Signal capture and intent activation", "Deep enrichment & fit scoring", "CRM and RevOps sync with stage hygiene", "Ranked routing queues and live reporting"], icon: Workflow }, { eyebrow: "Engine 02 · Marketing ops", title: "Account-Based Marketing", desc: "Pick the accounts that matter, wait for them to signal, then surround the buying committee.", bullets: ["Account tiering and signal activation", "Committee multi-threading", "Multichannel email, LinkedIn, and ad plays", "Visitor de-anonymisation and pipeline acceleration"], icon: Target }] },
    focus: { eyebrow: "Built for your stage", title: "From first pipeline to predictable scale.", desc: "The engine stays the same; what it is tuned for changes with your stage.", items: [{ eyebrow: "Pre-revenue · 0 → 1", title: "Find the motion that works", desc: "Turn product conviction into proof that a repeatable channel exists before hiring around it.", bullets: ["Define your ICP and buying committee", "Test message-market resonance", "Build a founder-led outbound motion"], icon: Target }, { eyebrow: "Series A+ · 1 → scale", title: "Make the motion compound", desc: "Turn scattered systems and growing pipeline pressure into a coordinated revenue engine.", bullets: ["Account-based segmentation", "RevOps orchestration", "Multi-threaded enterprise plays"], icon: BarChart3 }, { eyebrow: "The stack", title: "Build on a clean data model", desc: "Reliable data, orchestration, and activation — assembled in the order the system needs.", bullets: ["Buying-group model and lifecycle ownership", "Waterfall enrichment and auto-routing", "Deliverability infrastructure and live dashboards"], icon: Layers }] },
    metrics: [{ label: "Cost per meeting", value: "Tracked weekly", desc: "Fully-loaded cost of every qualified meeting." }, { label: "Signal-to-meeting time", value: "Days, not weeks", desc: "How fast an in-market signal becomes a conversation." }, { label: "Data match rate", value: "2–3× single-source", desc: "Coverage from multi-provider waterfall enrichment." }, { label: "CRM hygiene", value: "Automated", desc: "Duplicates, stages, and orphaned records handled by the system." }],
    faqs: [{ q: "What's the difference between ABM and traditional lead generation?", a: "Traditional lead gen is a volume game. ABM qualifies a specific list of target accounts first, then runs coordinated outreach only to them — less volume, higher conversion, and less spend wasted on accounts that cannot buy." }, { q: "Will this work for a highly technical product?", a: "It is where the model shines. Signal-based targeting and deep enrichment let us reach precise buying committees at the right moment instead of blasting a market that mostly cannot buy." }, { q: "Do we own what you build?", a: "You own the data model, Clay tables, workflows, and CRM configuration. You keep a working engine and can run it in-house." }, { q: "When will we see pipeline?", a: "A live signal-based motion can be running inside two weeks. We agree KPIs from real market data once the engine is live, never promised blind." }],
    final: { title: "Stop spraying. Start engineering.", desc: "Map the signals that matter in your market, the accounts worth chasing, and what a signal-based motion looks like for your stage.", cta: "Build your GTM system" },
  },
  "automation-transformation": {
    id: "automation-transformation", title: "AI Automation & Transformation", icon: Zap,
    heroLead: "Give your team", heroHighlight: "their week back.",
    intro: "The repetitive work — answering the same calls, retyping the same data, hunting through the same PDFs — isn't a headcount problem. It's an automation problem. We build custom AI agents that talk, read, and run, wired into the tools you already use, and we stay until they actually work in production.",
    primaryCta: "Map my workflows", secondaryCta: "Estimate hours saved", highlights: ["Custom AI agent deployment", "Production integration guarantee"],
    panel: { title: "Agents · deployed", badge: "status", rows: [{ label: "Voice receptionist", value: "24/7" }, { label: "Document brain", value: "indexing" }, { label: "Inbox & comms agent", value: "routing" }, { label: "CRM operator", value: "syncing" }, { label: "Invoice runner", value: "chasing" }] },
    stats: [{ value: "24/7", label: "agents that never miss a job" }, { value: "Weeks", label: "to a first agent on live work" }, { value: "Yours", label: "agents & integrations" }, { value: "1st", label: "workflow quietly pays for the next" }],
    challenge: { eyebrow: "The work hiding in plain sight", title: "Repetitive work is an automation problem.", desc: "Most teams don't need another tool or another hire. They need their existing tools, documents, and rules wired into reliable agents that handle the repeatable work.", oldLabel: "Manual operations", oldBullets: ["Calls missed after business hours", "PDFs, inboxes, and forms read by hand", "CRM records updated after the fact", "Follow-ups dependent on a busy team", "Knowledge trapped in people and documents"], newLabel: "Agents in production", newBullets: ["Voice, chat, and document agents around the clock", "Workflows grounded in your real rules", "Data moves between your existing tools", "Human oversight where it matters", "Monitoring that stays after launch"] },
    flow: { eyebrow: "How we work", title: "Map the work. Build the agent. Prove it live.", desc: "A focused implementation flow that starts with real work and ends with a production-ready system.", steps: [{ num: "01", title: "Map", desc: "Shadow the work. Find where hours actually leak and which of it is safely automatable." }, { num: "02", title: "Scope", desc: "Agree the specific workflows to automate and the outcome each one owns." }, { num: "03", title: "Build", desc: "Wire the agent into your tools, grounded in real documents and rules." }, { num: "04", title: "Test", desc: "Run it beside your team on live work, tuning until it is trustworthy." }, { num: "05", title: "Ship", desc: "Hand it over with monitoring, so it keeps running when we step back." }, { num: "06", title: "Iterate", desc: "Expand to the next workflow once the first is quietly paying for itself." }] },
    cards: { eyebrow: "What we build", title: "Three kinds of agents. One quieter workday.", desc: "Agents that talk, read, and run work together so a phone call becomes a booked job and a clean CRM record without retyping.", items: [{ eyebrow: "Agents that talk", title: "Voice & Chat", desc: "Answer, qualify, book, and follow up across phone, web, and messaging — in your voice, around the clock.", bullets: ["Voice AI reception", "Inbound qualification", "Booking & rescheduling", "Automated follow-up"], icon: PhoneCall }, { eyebrow: "Agents that read", title: "Documents & Data", desc: "Digest PDFs, contracts, forms, and inboxes, then answer questions and pull out what matters in seconds.", bullets: ["Document intelligence", "Field extraction", "Natural-language search", "Summarise & flag"], icon: FileText }, { eyebrow: "Agents that run", title: "Workflow Ops", desc: "Move data between tools, update the CRM, trigger the next step, and keep operations flowing.", bullets: ["Workflow orchestration", "CRM sync & enrichment", "Trigger-based actions", "Cross-tool integration"], icon: Workflow }] },
    focus: { eyebrow: "Industry plays", title: "Legacy business? Even better.", desc: "Where work is repeatable and knowledge is buried in PDFs and inboxes, agents earn their keep quickly.", items: [{ eyebrow: "Dental & clinics", title: "Fill the chair. End front-desk chaos.", desc: "An always-on front desk and a recall machine behind your practice.", bullets: ["Voice booking and rescheduling", "Eligibility checks", "Recall automation", "New-patient intake"], icon: Building2 }, { eyebrow: "Construction", title: "Win more bids. Drown in less paperwork.", desc: "RFPs, permits, and project updates become background workflows.", bullets: ["RFP extraction", "Bid and estimate drafts", "Compliance alerts", "Invoice generation"], icon: FileText }, { eyebrow: "Professional services", title: "Bill more hours. Do less admin.", desc: "Hand reading, drafting, and reconciling to agents so time returns to billable work.", bullets: ["Document review", "Client intake", "Proposal drafts", "Billing reconciliation"], icon: Bot }] },
    metrics: [{ label: "Hours saved", value: "Measured monthly", desc: "Time returned from repetitive administrative work." }, { label: "Automation share", value: "Workflow-specific", desc: "Only work that can be safely and reliably automated." }, { label: "Loaded cost", value: "Reclaimed", desc: "Cost redirected from routine tasks to higher-value work." }, { label: "Production readiness", value: "Live-work tested", desc: "Agents prove themselves alongside your team." }],
    faqs: [{ q: "We're not a tech company. Can we still do this?", a: "That is most of who we build for. We handle the technical half; you bring the knowledge of how the work actually gets done." }, { q: "We tried an AI tool before and it went nowhere. Why is this different?", a: "Generic tools fail because they do not know your business. We build around real workflows, documents, and rules, and stay until it works in production." }, { q: "Our data is messy and scattered. Is that a problem?", a: "It is the normal starting point. Digitising, connecting, and cleaning PDFs, inboxes, spreadsheets, and legacy systems is part of the build." }, { q: "Do we own it?", a: "You own the agents, workflows, and integrations, running on infrastructure you control." }],
    final: { title: "Put the repeatable work on autopilot.", desc: "Start with the workflow that costs your team the most time, then make the first live agent pay for the next.", cta: "Map my workflows" }, calculator: true,
  },
  "content-marketing": {
    id: "content-marketing", title: "Content Marketing", icon: FileText,
    heroLead: "Content that", heroHighlight: "compounds.",
    intro: "Most content marketing is a treadmill: publish, get buried, publish again. We run it as an engine instead — research-led, loaded with your positioning, and produced at a volume that builds a moat over six months. Depth a freelancer can't match, at a cadence an in-house writer can't hit.",
    primaryCta: "Plan my content engine", secondaryCta: "See the engine", highlights: ["Research-led context engine", "Dual SEO & AEO optimisation"],
    panel: { title: "Content engine · this month", badge: "team of 2", rows: [{ label: "Blog posts (SEO + AEO)", value: "8" }, { label: "Social pieces", value: "12" }, { label: "Videos + scripts", value: "4" }, { label: "Newsletter issues", value: "4" }, { label: "Founder LinkedIn", value: "ongoing" }] },
    stats: [{ value: "200+", label: "assets at sustained cadence" }, { value: "SEO + AEO", label: "optimised for search & answers" }, { value: "1 spine", label: "repurposed across channels" }, { value: "6 months", label: "to meaningful compounding" }],
    challenge: { eyebrow: "The content treadmill", title: "Publishing more is not a content strategy.", desc: "Blank-prompt output, disconnected social posts, and content calendars made without buyer context produce activity, not authority or pipeline.", oldLabel: "The content mill", oldBullets: ["Generic drafts without positioning or proof", "One-off posts that disappear after publishing", "SEO content detached from real buyer questions", "A founder voice that changes every week", "Reporting built on vanity metrics"], newLabel: "A compounding content engine", newBullets: ["Every asset starts with a buyer question and funnel stage", "Positioning, ICP, voice, and proof loaded into the brief", "Human QA that sharpens the point of view", "One research spine repurposed across channels", "SEO and AEO built in from the start"] },
    flow: { eyebrow: "The engine", title: "From a buyer question to a compounding distribution system.", desc: "Every piece follows a six-step system that keeps the voice, point of view, and proof intact at scale.", steps: [{ num: "01", title: "Brief", desc: "Anchor each piece to a buyer question, keyword cluster, and funnel stage." }, { num: "02", title: "Context", desc: "Load positioning, ICP, voice, and proof so the draft starts on-brand." }, { num: "03", title: "Draft", desc: "AI production at volume, grounded in context — not a blank-prompt guess." }, { num: "04", title: "QA", desc: "A human editor checks claims, sharpens the POV, and kills anything generic." }, { num: "05", title: "Polish", desc: "Format for the channel, add proof and links, optimise for SEO + AEO." }, { num: "06", title: "Ship", desc: "Publish, repurpose, and feed performance back into the briefs." }] },
    cards: { eyebrow: "What we produce", title: "One research spine. Many high-value formats.", desc: "A single deep piece becomes a blog post, video, social series, and newsletter section — reshaped for where buyers spend time.", items: [{ eyebrow: "Long-form", title: "Blog & Pillar Content", desc: "Depth pieces at positioning-level quality — the kind that ranks, gets cited, and gives sales something to send.", bullets: ["SEO + AEO pillar pages and clusters", "Comparison & alternative pages", "Point-of-view essays", "Case-study frameworks by vertical"], icon: FileText }, { eyebrow: "Short-form", title: "Social & Founder Content", desc: "The distribution layer that turns research into a credible founder voice.", bullets: ["LinkedIn posts & carousels", "X / Twitter threads", "Founder-led content strategy", "Repurposing from long-form"], icon: Share2 }, { eyebrow: "Video", title: "Scripts & Short Video", desc: "On-message video built from the same research, not a separate effort.", bullets: ["Video scripts & hooks", "Explainer narratives", "Blog-to-video-to-social pipeline", "Talking-head and voiceover formats"], icon: Video }, { eyebrow: "Owned audience", title: "Newsletter & Nurture", desc: "Keep a consistent, valuable channel running so inbound has somewhere to land and warm up.", bullets: ["Recurring newsletter issues", "Lifecycle nurture sequences", "Lead-magnet offers", "Segment-aware messaging"], icon: Mail }] },
    focus: { eyebrow: "Search + answers", title: "Build visibility where buyers now ask questions.", desc: "Traditional rankings still matter. So does being clear enough to be cited by answer engines.", items: [{ eyebrow: "SEO", title: "Rank for buyer intent", desc: "Build topical authority around the questions, comparisons, and categories buyers already search.", bullets: ["Keyword clusters", "Internal linking", "Structured landing pages", "Performance feedback"], icon: Search }, { eyebrow: "AEO", title: "Be cited by answer engines", desc: "Make depth, clarity, and claims easy for AI assistants to retrieve and trust.", bullets: ["Answer-led structure", "Proof-backed claims", "Clear entity coverage", "Citable expertise"], icon: Globe }, { eyebrow: "Measurement", title: "Map content to pipeline", desc: "Connect content output and distribution to the business outcomes it supports.", bullets: ["Funnel-stage reporting", "Organic reach and citations", "Sales enablement use", "Inbound conversion"], icon: BarChart3 }] },
    metrics: [{ label: "Content cadence", value: "200+/mo", desc: "A sustainable system instead of one-off production." }, { label: "Brand voice", value: "Context-loaded", desc: "Voice files and proof banks keep every format consistent." }, { label: "Answer engine", value: "AEO by default", desc: "Content structured for the way buyers increasingly search." }, { label: "Pipeline link", value: "Funnel-mapped", desc: "Reporting that ties output to buyer movement, not vanity metrics." }],
    faqs: [{ q: "Isn't AI-written content just spam Google will penalise?", a: "Bad AI content is. What we ship is research-led, context-loaded, and human-edited, so it is useful and original rather than thin or generic." }, { q: "How do you keep volume from tanking quality?", a: "Quality lives in the inputs. Every generation uses your positioning, ICP, voice, and proof bank, then passes a human quality gate before shipping." }, { q: "What is AEO?", a: "Answer Engine Optimisation makes content citable by AI assistants such as ChatGPT and Perplexity, which increasingly answer buyer questions directly." }, { q: "Do we own the content and system?", a: "Yes — the content, voice files, topic strategy, and workflows are yours." }],
    final: { title: "Stop filling a calendar. Start building a moat.", desc: "Turn your positioning and buyer insight into a content system that compounds across search, social, and your owned audience.", cta: "Plan my content engine" },
  },
  "investor-outreach": {
    id: "investor-outreach", title: "Investor Outreach", icon: TrendingUp,
    heroLead: "Fundraising is a pipeline.", heroHighlight: "Most founders run it on hope.",
    intro: "A raise is the highest-stakes outbound campaign a founder ever runs — and most run it with a spreadsheet of names, a generic deck, and cold DMs into the void. We engineer it like a sales motion: thesis-matched targeting, warm-path mapping, a narrative that lands, and every conversation tracked to the next step.",
    primaryCta: "Engineer my raise", secondaryCta: "See the system", highlights: ["Thesis-matched capital engine", "100% relationship control"],
    panel: { title: "Raise pipeline · live", badge: "this round", rows: [{ label: "Thesis-matched investors", value: "tiered" }, { label: "Warm intro paths", value: "mapped" }, { label: "First meetings", value: "booked" }, { label: "Data room", value: "ready" }, { label: "Follow-ups", value: "on track" }] },
    stats: [{ value: "Tiered", label: "fund & partner fit" }, { value: "Warm", label: "paths mapped first" }, { value: "Tracked", label: "every investor thread" }, { value: "Yours", label: "relationships & CRM" }],
    challenge: { eyebrow: "The way most raises go", title: "A raise run on hope burns your best asset: time.", desc: "Founders who close fast are not luckier. They target the right investors, reach them warm, tell one crisp story, and never let a thread go cold.", oldLabel: "Spray & pray raise", oldBullets: ["A list of 400 investors with no thesis fit", "Cold DMs that get read and ignored", "A deck that explains the product but not the wedge", "No warm paths, so every intro starts from zero trust", "Conversations that go quiet with no follow-up system"], newLabel: "Engineered by Leadnius", newBullets: ["A tiered list matched to each fund's thesis", "Warm-path mapping through your network", "A narrative that leads with the wedge", "Prioritised intros to the best-fit funds", "A tracked pipeline where no thread goes cold"] },
    flow: { eyebrow: "The raise pipeline", title: "From target list to term sheet conversations.", desc: "Six stages run like a go-to-market motion, turning a founder's network and story into a prioritised, tracked pipeline.", steps: [{ num: "01", title: "Target", desc: "Build a thesis-matched, tiered investor list by stage, sector, cheque size, and recent activity." }, { num: "02", title: "Map", desc: "Trace warm paths from your team, cap table, and network to each target fund." }, { num: "03", title: "Frame", desc: "Align deck, one-pager, and data room to one story." }, { num: "04", title: "Reach", desc: "Sequence warm intros first, then personalised cold outreach where needed." }, { num: "05", title: "Track", desc: "Run every conversation through an investor CRM with clear next steps." }, { num: "06", title: "Advance", desc: "Follow up on cadence, manage diligence requests, and keep momentum toward a close." }] },
    cards: { eyebrow: "What we build", title: "The full outreach machine, assembled for one round.", desc: "Every part of the raise operates as one focused, founder-owned system.", items: [{ eyebrow: "01 · Targeting", title: "Thesis-Matched Investor List", desc: "We match funds to stage, sector, geography, cheque size, and what they have actually funded lately.", bullets: ["Tiered by fit and priority", "Partner-level, not just fund-level", "Recent-activity and thesis signals"], icon: Target }, { eyebrow: "02 · Warm paths", title: "Introduction Mapping", desc: "Mine your team, cap table, advisors, and network to find the warmest route to each target.", bullets: ["Network graph across connections", "Best-path routing to each fund", "Intro-request templates"], icon: Workflow }, { eyebrow: "03 · Narrative", title: "Story, Deck & Data Room Alignment", desc: "One story, told consistently across your wedge, deck, and diligence materials.", bullets: ["Investor narrative & wedge", "Deck structure review", "Data-room checklist"], icon: FileText }, { eyebrow: "04 · Outreach", title: "Sequenced Outreach + Investor CRM", desc: "Warm intros first, personalised cold outreach where needed, and every thread tracked.", bullets: ["Personalised sequences", "Investor CRM stages", "Follow-up cadence"], icon: Send }] },
    focus: { eyebrow: "Stage fit", title: "A sharper process at every stage of the raise.", desc: "The process is designed to protect runway and momentum, before or during a live round.", items: [{ eyebrow: "Pre-seed & seed", title: "Make the wedge unmistakable", desc: "Find the investors who fit the earliest version of the story and activate warm support quickly.", bullets: ["Category and wedge clarity", "Target list by conviction", "Founder-network mapping"], icon: Target }, { eyebrow: "Series A+", title: "Run a disciplined investor process", desc: "Coordinate a more complex story, data room, and stakeholder process without losing speed.", bullets: ["Partner-level prioritisation", "Diligence readiness", "Pipeline management"], icon: BarChart3 }, { eyebrow: "Relationship ownership", title: "Keep the relationships", desc: "Leadnius runs the process in the background; every investor relationship remains founder-owned.", bullets: ["Your target list", "Your investor CRM", "Your conversations"], icon: TrendingUp }] },
    metrics: [{ label: "Target quality", value: "Thesis-matched", desc: "Funds and partners ranked by genuine fit." }, { label: "Warm paths", value: "Mapped", desc: "Best route from the network you already have." }, { label: "Investor CRM", value: "Founder-owned", desc: "Every stage and next step stays visible." }, { label: "Fundraising control", value: "Always yours", desc: "No broker model and no percentage of the round." }],
    faqs: [{ q: "Can you guarantee we'll raise the round?", a: "No. Whether you raise depends on the business, metrics, and market conditions. We control the process: target quality, warm intros, narrative, and follow-up discipline." }, { q: "Are you a broker or financial advisor?", a: "No. Leadnius supports targeting, introductions, narrative, and pipeline management. We are not a broker-dealer or placement agent and do not give financial, investment, or legal advice." }, { q: "Who owns the investor relationships?", a: "You do, entirely. Every conversation is founder-to-investor, and you keep the CRM, relationships, and target list." }, { q: "When should we start?", a: "Earlier than most founders think. Targeting, narrative, warm-path mapping, and data-room preparation work best before the round goes live." }],
    final: { title: "Run your raise like the pipeline it is.", desc: "Get the right investors, the warmest routes, and the discipline that keeps every valuable conversation moving.", cta: "Engineer my raise" },
  },
};
